[package]
name = "rusty-store"
version = "0.1.0"
authors = ["Antoine Cheneau <antoine.cheneau@outlook.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }

[dev-dependencies]
redis = "*"
